name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  IMAGE_NAME: particula-authentication-api
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag particula-authentication-api
        
  deploy:
    name: deploy
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOYMENT_SERVER_HOST }}
        username: ${{ secrets.DEPLOYMENT_SERVER_USERNAME }}
        key: ${{ secrets.DEPLOYMENT_SERVER_KEY }}
        port: ${{ secrets.DEPLOYMENT_SERVER_PORT }}
        script: |
          cd ${{ secrets.DEPLOYMENT_SERVER_PATH }}
          docker-compose pull authentication_api
          docker-compose up -d authentication_api
